#!/usr/bin/env python3

from modules.storage_management import *
from discord.ext import commands
import discord
import os
import aiosqlite
import sqlite3

from modules import first_run

if os.environ.get('MOMIJI_TOKEN'):
    bot_token = os.environ.get('MOMIJI_TOKEN')
else:
    try:
        with open(dirs.user_data_dir + "/token.txt", "r+") as token_file:
            bot_token = token_file.read().strip()
    except FileNotFoundError as e:
        print("i need a bot token. either set MOMIJI_TOKEN environment variable")
        print("or put it in token.txt in my AppData/.config folder")
        raise SystemExit

if os.environ.get('MOMIJI_PREFIX'):
    command_prefix = os.environ.get('MOMIJI_PREFIX')
else:
    command_prefix = ";"

first_run.ensure_tables()

initial_extensions = [
    "cogs.AIMod",
    "cogs.BotManagement",
    "cogs.ChannelExporting", 
    "cogs.COVID19",
    "cogs.CRPair",
    "cogs.DMManagement",
    "cogs.Fun",
    "cogs.Gatekeeper",
    "cogs.Img",
    "cogs.InspiroBot", 
    "cogs.LegacyWaifu",
    "cogs.MessageStats",
    "cogs.Misc",
    "cogs.GoodbyeMessage",
    "cogs.Moderation", 
    "cogs.MomijiChannelImporting", 
    "cogs.MomijiCommands", 
    "cogs.MomijiSpeak", 
    "cogs.Music", 
    "cogs.Pinning", 
    "cogs.RegularRole",
    "cogs.Reminders",
    "cogs.RSSFeed",
    "cogs.SelfAssignableRoles",
    "cogs.StatsBuilder", 
    "cogs.TraceMoe",
    "cogs.UserPreferences",
    "cogs.Utilities",
    "cogs.VoiceLogging",
    "cogs.VoiceRoles", 
    "cogs.Waifu",
    "cogs.Wasteland",
    "cogs.WastelandConfiguration",
    "cogs.WelcomeMessage",
]

intents = discord.Intents.default()
intents.members = True


class Momiji(commands.Bot):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.background_tasks = []
        self.app_version = (open(".version", "r+").read()).strip()
        self.description = f"Momiji {self.app_version}"
        self.database_file = database_file
        self.shadow_guild = None

        conn = sqlite3.connect(self.database_file)
        c = conn.cursor()
        self.bridged_extensions = tuple(c.execute("SELECT extension_name FROM bridged_extensions"))
        self.user_extensions = tuple(c.execute("SELECT extension_name FROM user_extensions"))
        conn.close()

        for extension in initial_extensions:
            try:
                self.load_extension(extension)
            except discord.ext.commands.errors.ExtensionNotFound as ex:
                print(ex)

        for bridged_extension in self.bridged_extensions:
            try:
                self.load_extension(bridged_extension[0])
                print(f"Bridged extension {bridged_extension[0]} loaded")
            except discord.ext.commands.errors.ExtensionNotFound as ex:
                print(ex)

        for user_extension in self.user_extensions:
            try:
                self.load_extension(user_extension[0])
                print(f"User extension {user_extension[0]} loaded")
            except discord.ext.commands.errors.ExtensionNotFound as ex:
                print(ex)

    async def start(self, *args, **kwargs):
        self.db = await aiosqlite.connect(self.database_file)

        await super().start(*args, **kwargs)

    async def close(self):
        # Cancel all Task object generated by cogs.
        # This prevents any task still running due to having long sleep time.
        for task in self.background_tasks:
            task.cancel()

        # Close connection to the database
        await self.db.close()

        # Run actual discord.py close.
        # await super().close()

        # for now let's just quit() since the thing above does not work :c
        quit()

    async def on_ready(self):
        print("Logged in as")
        print(self.user.name)
        print(self.user.id)
        print("------")
        await first_run.add_admins(self)


client = Momiji(command_prefix=command_prefix, intents=intents)
client.run(bot_token)
